name: Scala formatter
on:
  push:
    branches: [ main ]
    paths:
      - '**.scala'
  pull_request:
    branches: [ main ]
    paths:
      - '**.scala'

jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be escaped and space-delimited.
        # Output is usable as command-line argument list in Linux shell
        list-files: shell
        fetch-depth: 10
        # In this example changed files will be checked by linter.
        # It doesn't make sense to lint deleted files.
        # Therefore we specify we are only interested in added or modified files.
          filters: |
            scala:
              - added|modified: '**.scala'
    - name: Check for scalafmt conformance
      if: ${{ steps.filter.outputs.scala == 'true' }}
      run: |
        VERSION=3.5.8
        INSTALL_LOCATION=/usr/bin/scalafmt-native
        curl https://raw.githubusercontent.com/scalameta/scalafmt/master/bin/install-scalafmt-native.sh | \
        sudo bash -s -- $VERSION $INSTALL_LOCATION
        scalafmt-native --help
        echo "---------------------------------------------------"
        scalafmt-native ${{ steps.filter.outputs.scala_files }} --check --reportError
